sudo: false
language: node_js
addons:
  chrome: stable
matrix:
  fast_finish: true
node_js:
  - "11.15.0"
notifications:
  email: false
before_install:
  - npm install -g @lhci/cli@0.3.x
  - npm i -g npm@6.9.0
install: npm run bootstrap
script:
  - npm run build
  - npm run test
after_success:
  - lhci autorun --upload.target=temporary-public-storage # run lighthouse CI against build artifacts
