name: Remote Config Backup Download
description: Download remote config backup
inputs:
  REMOTE_CONFIG_URL:
    description: "Remote config backup URL"
runs:
  using: composite
  steps:
    - name: Setup Environment variables
      run: |
        echo "REMOTE_CONFIG_URL=${{ inputs.REMOTE_CONFIG_URL }}" >> "$GITHUB_ENV"
      shell: bash
    - name: Download remote config backup
      run: |
        echo "Downloading remote config backup"
        curl $REMOTE_CONFIG_URL > packages/api/src/remote_config.json
        echo "Remote Config backup downloaded successfully!"
      shell: bash
