name: versioning
description: Versioning
inputs:
  release_type:
    description: Release Type
    required: false
runs:
  using: composite
  env: 
    RELEASE_TYPE: ${{ inputs.release_type }}
  steps:
  - name: Tag version
      run: echo "$(echo "($RELEASE_TYPE)-$(date -u +"%Y-%m-%dT%H:%M:%SZ")")" > packages/core/dist/version
    shell: bash
