name: send_slack_notification
description: Send Slack notification
inputs:
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook URL'
    required: true
  MESSAGE:
    description: 'Status message'
    required: true
runs:
  using: composite
  steps:
  - name: Send Slack Notification
    env:
      SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
      MESSAGE: ${{ inputs.MESSAGE }}
    run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
        "text": "$MESSAGE"
        }' \
          $SLACK_WEBHOOK_URL
    shell: bash
