name: send_slack_notifications
description: Send Slack notifications
inputs:
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook URL'
    required: true
  status:
    description: 'Job status'
    required: true
  release_type:
    description: 'Release type'
    required: true
  version:
    description: 'Version'
    required: true
    default: 'N/A'
runs:
  using: composite
  steps:
  - name: Send Slack Notification on Success
    env:
      SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
      RELEASE_TYPE: ${{ inputs.release_type }}
      VERSION: ${{ inputs.version }}

    if: inputs.status == 'success'
    run: |-
        curl -X POST -H 'Content-type: application/json' \
        --data '{
        "text": "$RELEASE_TYPE Release succeeded for app.deriv.com with version *'$VERSION'*"
        }' \
          $SLACK_WEBHOOK_URL
    shell: bash
  
  - name: Send Slack Notification on Failure
    if: inputs.status == 'failure'
    run: |-
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "$RELEASE_TYPE Release failed for app.deriv.com with version *'"$VERSION"'*"
          }' \
          $SLACK_WEBHOOK_URL
    shell: bash
