name: send_slack_notification
description: Send Slack notification
inputs:
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook URL'
    required: true
  MESSAGE:
    description: 'Status message'
    required: true
runs:
  using: composite
  steps:
  - name: Setup Environment variables
    run: |
      echo "SLACK_WEBHOOK_URL=${{ inputs.SLACK_WEBHOOK_URL }}" >> "$GITHUB_ENV"
      echo "MESSAGE=${{ inputs.MESSAGE }}" >> "$GITHUB_ENV"
    shell: bash
  - name: Send Slack Notification
    run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
        "text": "$MESSAGE"
        }' \
          $SLACK_WEBHOOK_URL
    shell: bash
