name: Deriv App ID Generator

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write
  statuses: write

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
    generate_app_id:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: Comment on pull request with App ID and URLs
              id: sticky_comment_on_pr
              uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  header: deriv-app-id-action
                  message: |
                      Last attempt to comment out stuff