name: Build Docker image for Passkey
on:
  pull_request:
    branches:
    - build_docker_passkey_image
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract Branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.WEB_ACCESS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.WEB_ACCESS_DOCKERHUB_PASSWORD }}
      
      - name: Run Bootstrap
        run: npm run bootstrap

      - name: Run Build:prod
        run: npm run build:prod

      - name: Run Build Docker
        run: docker build -t ${{ secrets.WEB_ACCESS_DOCKERHUB_USERNAME }}/${{ steps.extract_branch.outputs.branch }} . --platform=linux/amd64
      
      - name: Run Tag Docker
        run: docker tag ${{ secrets.WEB_ACCESS_DOCKERHUB_USERNAME }}/${{ steps.extract_branch.outputs.branch }} ${{ secrets.WEB_ACCESS_DOCKERHUB_USERNAME }}/${{ steps.extract_branch.outputs.branch }}

      - name: Run Push Docker
        run: docker push ${{ secrets.WEB_ACCESS_DOCKERHUB_USERNAME }}/${{ steps.extract_branch.outputs.branch }}