on: 
  pull_request:
  push:
    branches:
      - master

name: Coveralls

jobs:

  build:
    name: Reporter
    runs-on: Runner_16cores_Deriv-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"
      - name: Build
        uses: "./.github/actions/build"
      - name: Run tests
        run: npm run test:jest -- --collectCoverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
