on: 
  pull_request:
  push:
    branches:
      - master

name: Coveralls

jobs:

  build:
    name: Reporter
    runs-on: Runner_16cores
    container:
      image: node:18.16.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"
      - name: Build
        uses: "./.github/actions/build"
      - name: Run tests
        run: npm run test:jest
      - name: Coveralls
        uses: coverallsapp/github-action@v2
