on: ["pull_request"]

name: Coveralls

jobs:

  build:
    name: Reporter
    runs-on: Runner_16cores_Deriv-app
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"
      - name: Build
        uses: "./.github/actions/build"
      - name: Test
        run: JEST_MAX_WORKERS=14 npm run test:jest -- --collectCoverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
