name: Run Smoke Tests - Manually
run-name: Manual run of ${{ github.event.inputs.suite }} tests on ${{ github.event.inputs.testlink || github.event.inputs.environment }} in ${{ github.event.inputs.qabox }} ${{ github.event.inputs.appid }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - https://staging-app.deriv.com/
        - https://app.deriv.com/
        - https://test-app.deriv.com
      suite:
        type: choice
        description: Run smoke or full test suite
        options:
        - full
        - smoke
        - full/P2P
        - smoke/P2P
        - api
        - wip/CFD/testcases/MT5
        - wip/dbot/sanity-tests
        - wip/Wallets
        - wip/dtrader
        - wip/P2P
        - wip/Tradershub
        - wip/cashierLegacy
        - full_extended
        - wip/KYC
      qabox:
        type: number
        required: false
        description: (Optional) Enter QA box number.
      appid:
        type: number
        required: false
        description: (Optional) Enter app ID.
      testlink:
        type: string
        required: false
        description: (Optional) Enter your test URL.
      testcase:
        type: string
        description: (Optional) Run one spec file (e.g. signUpPage.cy.js) or leave it blank to run all tests in the selected test suite.
        required: false
      branches:
        type: string
        description: (Optional) Enter your branch name.

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      # matrix:
      #  containers: [1,2]

    steps:
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Checkout external repository with Cypress tests
      env:
        e2e_branch: ${{github.event.inputs.branches}}
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        repository: deriv-com/e2e-deriv-app # Replace with your repository name
        ref: ${{ env.e2e_branch }}

    - name: Create server URL
      env:
        QA_BOX: ${{github.event.inputs.qabox}}
      if: ${{github.event.inputs.qabox !='' }}
      run: echo QA_SERVER=qa"$QA_BOX".deriv.dev >> $GITHUB_ENV

    - name: Update baseURL if using test URL
      env:
        TEST_LINK: ${{github.event.inputs.testlink}}
      if: ${{github.event.inputs.testlink !='' }}
      run: echo TEST_URL="$TEST_LINK" >> $GITHUB_ENV

    - name: Set Recording Variable
      run: |
        if [ "${{ github.event.inputs.suite }}" == "full_extended" ]; then
          echo RECORD=false >> $GITHUB_ENV
          echo ${{ env.RECORD }}
        else
          echo RECORD=true >> $GITHUB_ENV
          echo ${{ env.RECORD }}
        fi

    - name: Cypress run
      uses: cypress-io/github-action@1b70233146622b69e789ccdd4f9452adc638d25a
      with:
        record: ${{ env.RECORD }}
        parallel: false
        spec: cypress/e2e/${{env.TEST_SUITE}}/${{env.TEST_CASE}}
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_BASE_URL: "${{ env.TEST_URL || github.event.inputs.environment }}"
        COMMIT_INFO_MESSAGE: Manual Run of "${{ github.event.inputs.suite }} tests" on "${{ github.event.inputs.environment }}"
        # Set test env variables
        TEST_CASE: ${{github.event.inputs.testcase}}
        E2E_DERIV_LOGIN: ${{ secrets.E2E_DERIV_LOGIN }}
        E2E_DERIV_PASSWORD: ${{ secrets.E2E_DERIV_PASSWORD }}
        E2E_CONFIG_APPID: ${{ github.event.inputs.appid || secrets.E2E_CONFIG_APPID }}
        E2E_CONFIG_SERVER: ${{ env.QA_SERVER || secrets.E2E_CONFIG_SERVER }}
        E2E_OAUTH_URL: ${{ secrets.E2E_OAUTH_URL }}
        E2E_MT5_LOGIN: ${{ secrets.E2E_MT5_LOGIN }}
        E2E_MT5_PASSWORD: ${{ secrets.E2E_MT5_PASSWORD }}
        E2E_MT5_BASEURL: ${{ secrets.E2E_MT5_BASEURL }}
        E2E_STD_CONFIG_SERVER: ${{ env.QA_SERVER || secrets.E2E_STD_CONFIG_SERVER }}
        E2E_STD_CONFIG_APPID: ${{ github.event.inputs.appid || secrets.E2E_STD_CONFIG_APPID }}
        E2E_DOUGHFLOW_CONFIG_SERVER: ${{ secrets.E2E_DOUGHFLOW_CONFIG_SERVER }}
        E2E_DOUGHFLOW_CONFIG_APPID: ${{ secrets.E2E_DOUGHFLOW_CONFIG_APPID }}
        E2E_QABOX_URL: ${{ secrets.E2E_QABOX_URL }}
        E2E_MAIN_QABOX_URL: ${{ secrets.E2E_MAIN_QABOX_URL }}
        E2E_QABOX_LOGIN: ${{ secrets.E2E_QABOX_LOGIN }}
        E2E_QABOX_PASSWORD: ${{ secrets.E2E_QABOX_PASSWORD }}
        TEST_SUITE: ${{ github.event.inputs.suite }}
        E2E_DERIV_LOGIN_PROD: ${{secrets.E2E_DERIV_LOGIN_PROD}}
        E2E_DERIV_PASSWORD_PROD: ${{secrets.E2E_DERIV_PASSWORD_PROD }}
        E2E_PROD_SERVER: ${{secrets.E2E_PROD_SERVER}}
        E2E_PROD_APPID: ${{secrets.E2E_PROD_APPID}}
        E2E_LOGIN_ID_P2P_FIXEDRATE: ${{ secrets.E2E_LOGIN_ID_P2P_FIXEDRATE }}
        E2E_P2P_FLOATING: ${{secrets.E2E_P2P_FLOATING}}
        E2E_LOGIN_ID_P2P_STANDARDACCOUNTWITHADS: ${{secrets.E2E_LOGIN_ID_P2P_STANDARDACCOUNTWITHADS}}
        E2E_LOGIN_ID_P2P_STANDARDACCOUNTWITHOUTADS: ${{secrets.E2E_LOGIN_ID_P2P_STANDARDACCOUNTWITHOUTADS}}
        E2E_LOGIN_ID_P2P_FLOATINGRATE_SELLAD_1: ${{secrets.E2E_LOGIN_ID_P2P_FLOATINGRATE_SELLAD_1}}
        E2E_LOGIN_ID_P2P_FLOATINGRATE_SELLAD_2: ${{secrets.E2E_LOGIN_ID_P2P_FLOATINGRATE_SELLAD_2}}
        E2E_LOGIN_ID_P2P_EMPTYSTATE: ${{secrets.E2E_LOGIN_ID_P2P_EMPTYSTATE}}
        E2E_LOGIN_ID_P2P_SORT: ${{secrets.E2E_LOGIN_ID_P2P_SORT}}
        E2E_CRYPTO: ${{secrets.E2E_CRYPTO}}
        E2E_STG_APPID: ${{secrets.E2E_STG_APPID}}
        E2E_PSWD_P2P: ${{secrets.E2E_PSWD_P2P}}
        E2E_CASHIER_WITHDRAWAL_PROD: ${{secrets.E2E_CASHIER_WITHDRAWAL_PROD}}
        E2E_CASHIER_PROD_PASSWORD: ${{secrets.E2E_CASHIER_PROD_PASSWORD}}
        E2E_LOGIN_ID_DBOT: ${{secrets.E2E_LOGIN_ID_DBOT}}
        E2E_LOGIN_ID_PROD_DBOT: ${{secrets.E2E_LOGIN_ID_PROD_DBOT}}
        E2E_QA_ACCOUNT_PASSWORD: ${{secrets.E2E_QA_ACCOUNT_PASSWORD}}
        E2E_LOGIN_ID_CASHIER_LEGACY: ${{secrets.E2E_LOGIN_ID_CASHIER_LEGACY}}
        E2E_LOGIN_ID_CASHIER_LEGACY_NON_USD: ${{secrets.E2E_LOGIN_ID_CASHIER_LEGACY_NON_USD}}
        E2E_MAILISK_NAMESPACE: ${{secrets.E2E_MAILISK_NAMESPACE}}
        E2E_MAILISK_API_KEY: ${{secrets.E2E_MAILISK_API_KEY}}
        E2E_DIEL_LOGIN: ${{secrets.E2E_DIEL_LOGIN}}
        E2E_EU_LOGIN: ${{secrets.E2E_EU_LOGIN}}
        E2E_APP_REGISTER_URL: ${{secrets.E2E_APP_REGISTER_URL}}
        E2E_RUN_FROM_PR: ${{secrets.E2E_RUN_FROM_PR}}
      
