name: Run Smoke Tests - Manually
run-name: Manual run of tests

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
        
    - name: Trigger deriv-app smoke tests from regentmarkets
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.E2E_WORKFLOW_TOKEN }}
        script: |
          const workflowInputs = {
            environment: '${{ secrets.E2E_WORKFLOW_ENV }}',
            suite: '${{ secrets.E2E_WORKFLOW_ENV }}',
            appRegUrl: 'https://deriv-app-git-fork-maryia-matskevich-deriv-maryia-bot-1913.binary.sx/',
            issue_number: '15719',
            user_name: 'maryia-deriv'
            };
          const response = await github.rest.actions.createWorkflowDispatch({
            owner: 'regentmarkets',
            repo: 'e2e-deriv-app',
            workflow_id: 'E2E_Run_PR.yml',
            ref: 'mark/pr-commit-v2',
            inputs: workflowInputs
          });
          console.log('Workflow dispatched successfully:', response);

