name: Run Smoke Tests - Manually
run-name: Manual run of tests

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another deriv-app smoke tests from regentmarkets
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.E2E_WORKFLOW_TOKEN }}
          script: |
            const workflowInputs = {
              environment: '${{ secrets.E2E_WORKFLOW_ENV }}',
              suite: '${{ secrets.E2E_WORKFLOW_SUITE }}',
              triggeredByPR: 'true',
              appRegUrl: 'https://deriv-app-git-fork-suisin-deriv-suisin-upm917addswahililanguage.binary.sx',
              recKey: '${{ secrets.CYPRESS_RECORD_KEY }}'
              };
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: 'regentmarkets',
              repo: 'e2e-deriv-app',
              workflow_id: 'E2E_Run_v2.yml',
              ref: 'rajendra/appRegisterTest',
              inputs: workflowInputs
            });
            console.log('Workflow dispatched successfully:', response);
