name: Deriv App Test Workflow
on:
  pull_request:
    branches:
    - master
jobs:
  build_and_test:
    name: Build And Test
    runs-on: Runner_16cores_Deriv-app
    environment: Preview
    steps:
    - name: Checkout 
      uses: actions/checkout@v4


  send_slack_notification:
    name: Send Slack notification
    runs-on: Runner_16cores_Deriv-app
    environment: Production
    if: always()
    needs: [build_and_test]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Conclusion
      uses: technote-space/workflow-conclusion-action@v3
    - name: Extract version
      run: echo "VERSION_NO=$(cat packages/core/dist/version)" >> $GITHUB_ENV
    - name: Send Slack Notification
      uses: "./.github/actions/send_slack_notifications"
      with:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        status: ${{ env.WORKFLOW_CONCLUSION }}
        release_type: TEST_PLEASE_IGNORE 
        version: ${{ env.VERSION_NO }}