name: Deriv App PR Test Workflow
on:
  pull_request:
    branches:
    - master

jobs:
  test_slack_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Test Slack Notification
      uses: "./.github/actions/send_slack_notifications"
      with:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MESSAGE: "[TEST] Slack Notification Test"
